### ISSUE TITLE
windows binary

### ISSUE THREAD

**Issue by jtyuill** [xXCoolinXx/xo-rs#1]
hi i am from brasil could it be possible that there is windows binary !?!?!!? tanks :v :D

**Comment by xXCoolinXx** [comment]
Hello Windows user 
Your compare is infected by a very bad virus (Windows)
I recommend buying a Lenovo Thinkpad and installing libreboot and Linux on it to remove the the virus.

That being said , I have compiled a release for windows which can be found on the [release page](https://github.com/xXCoolinXx/xo-rs/releases/tag/v0.5.1).
You can additionally compile the program yourself as noted in the Readme.
